stages:
  - test
  - deploy

link_check:
  image: node:latest
  stage: test
  only:
    - merge_requests
  script:
    - npm install
    - node check_links.js

redirect_check:
  image: node:latest
  stage: test
  only:
    - merge_requests
  script:
    - npm install
    - node check_redirect.js

deploy:
  image: google/cloud-sdk
  stage: deploy
  only:
    - master
  script:
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_KEY
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/$GCP_CONTAINER_NAME:$CI_COMMIT_SHORT_SHA --gcs-log-dir=$GCS_LOG_DIR
    - gcloud run deploy $GCP_RUN_SERVICE --image gcr.io/$GCP_PROJECT_ID/$GCP_CONTAINER_NAME:$CI_COMMIT_SHORT_SHA --region=us-west1 --platform managed --port 8080
