image: google/cloud-sdk

deploy:
  stage: deploy
  only:
    - master
  script:
#    - export GOPATH=$HOME
#    - cp -r $CI_PROJECT_DIR $HOME
#    - cd $HOME/$CI_PROJECT_NAME
    - echo $GCP_SERVICE_KEY > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/$GCP_CONTAINER_NAME:$CI_COMMIT_SHORT_SHA
    - gcloud run deploy $GCP_RUN_SERVICE --image gcr.io/$GCP_PROJECT_ID/$GCP_CONTAINER_NAME:$CI_COMMIT_SHORT_SHA --region=us-west1 --platform managed --port 8080
